export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCES";

export const SET_USER = "SET_USER";
export const SET_MYPLAYLIST = "SET_MYPLAYLIST";

export const SET_NEW_RELEASES_BROWSE = "SET_NEW_RELEASES_BROWSE";
export const SET_RECOMMENDATIONS_BROWSE = "SET_RECOMMENDATIONS_BROWSE";
export const SET_RECENTLY_PLAYED = "SET_HAPPY_BROWSE";
export const SET_TOP_ARTISTS_BROWSE = "SET_TOP_ARTISTS_BROWSE";
